version: "3.8"

x-env:
  nats: &nats
    image: nats:2.8-alpine3.15
    networks:
      - backend
    restart:
      unless-stopped
  environment: &environment
    MY_NATS_ROUTE_USERNAME: "${MY_NATS_ROUTE_USERNAME}"
    MY_NATS_ROUTE_PASSWORD: "${MY_NATS_ROUTE_PASSWORD}"
    MY_NATS_NKEY_USER: "${MY_NATS_NKEY_USER}"
    MY_NATS_NKEY_SEED: "${MY_NATS_NKEY_SEED}"
    MY_NATS_USERNAME: "${MY_NATS_USERNAME}"
    MY_NATS_PASSWORD: "${MY_NATS_PASSWORD}"
    MY_MQTT_USERNAME: "${MY_MQTT_USERNAME}"
    MY_MQTT_PASSWORD: "${MY_MQTT_PASSWORD}"

services:
  nats1:
    <<: *nats
    command: "--name ${MY_NATS_SERVER_NAME}1 -c /etc/nats/nats-cluster.conf --user ${MY_NATS_ROUTE_USERNAME} --pass ${MY_NATS_ROUTE_PASSWORD} -js -D --routes nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats2:6222,nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats3:6222"
    environment:
      MY_NATS_SERVER_NAME: "${MY_NATS_SERVER_NAME}1"
      <<: *environment
    ports:
      # for clients
      - 4223:4222
      # an HTTP management port for information reporting
      - 8223:8222
    volumes:
      - $PWD/nats-cluster.conf:/etc/nats/nats-cluster.conf:ro
      - $PWD/nats-single.conf:/etc/nats/nats-single.conf:ro
      - data1:/data/jetstream
  nats2:
    <<: *nats
    command: "--name ${MY_NATS_SERVER_NAME}2 -c /etc/nats/nats-cluster.conf --user ${MY_NATS_ROUTE_USERNAME} --pass ${MY_NATS_ROUTE_PASSWORD} -js -D --routes nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats1:6222,nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats3:6222"
    environment:
      MY_NATS_SERVER_NAME: "${MY_NATS_SERVER_NAME}2"
      <<: *environment
    ports:
      # for clients
      - 4224:4222
      # an HTTP management port for information reporting
      - 8224:8222
    volumes:
      - $PWD/nats-cluster.conf:/etc/nats/nats-cluster.conf:ro
      - $PWD/nats-single.conf:/etc/nats/nats-single.conf:ro
      - data2:/data/jetstream
  nats3:
    <<: *nats
    command: "--name ${MY_NATS_SERVER_NAME}3 -c /etc/nats/nats-cluster.conf --user ${MY_NATS_ROUTE_USERNAME} --pass ${MY_NATS_ROUTE_PASSWORD} -js -D --routes nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats1:6222,nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats2:6222"
    environment:
      MY_NATS_SERVER_NAME: "${MY_NATS_SERVER_NAME}3"
      <<: *environment
    ports:
      # for clients
      - 4225:4222
      # an HTTP management port for information reporting
      - 8225:8222
    volumes:
      - $PWD/nats-cluster.conf:/etc/nats/nats-cluster.conf:ro
      - $PWD/nats-single.conf:/etc/nats/nats-single.conf:ro
      - data3:/data/jetstream

# networks
networks:
  backend:
    driver: bridge

volumes:  
  data1:
  data2:
  data3:
