version: "3.8"

services:
  nats:
    image: nats:2.8-alpine3.15
    command: "--name ${MY_NATS_SERVER_NAME} -c /etc/nats/nats-single.conf -js -D"
    environment:
      MY_NATS_SERVER_NAME: ${MY_NATS_SERVER_NAME}
      MY_NATS_ROUTE_USERNAME: ${MY_NATS_ROUTE_USERNAME}
      MY_NATS_ROUTE_PASSWORD: ${MY_NATS_ROUTE_PASSWORD}
      MY_LEAFNODE_USERNAME: ${MY_LEAFNODE_USERNAME}
      MY_LEAFNODE_PASSWORD: ${MY_LEAFNODE_PASSWORD}
      MY_NATS_NKEY_USER: ${MY_NATS_NKEY_USER}
      MY_NATS_NKEY_SEED: ${MY_NATS_NKEY_SEED}
      MY_NATS_USERNAME: ${MY_NATS_USERNAME}
      MY_NATS_PASSWORD: ${MY_NATS_PASSWORD}
      MY_MQTT_USERNAME: ${MY_MQTT_USERNAME}
      MY_MQTT_PASSWORD: ${MY_MQTT_PASSWORD}
    ports:
      # for clients
      - 4222:4222
      # an HTTP management port for information reporting
      - 8222:8222
    volumes:
      - $PWD/nats-single.conf:/etc/nats/nats-single.conf:ro
      - data:/data/jetstream
    restart:
      unless-stopped

volumes:  
  data:
