version: "3.8"
services:
  nats1:
    image: nats:2.6.6-alpine3.14
    command: "--name nats1 -c /etc/nats/nats-server.conf --user ${NATS_ROUTE_USERNAME} --pass ${NATS_ROUTE_PASSWORD} -js -D --routes nats-route://${NATS_ROUTE_USERNAME}:${NATS_ROUTE_PASSWORD}@nats2:6222,nats-route://${NATS_ROUTE_USERNAME}:${NATS_ROUTE_PASSWORD}@nats3:6222"
    environment:
      - NATS_ROUTE_USERNAME=${NATS_ROUTE_USERNAME}
      - NATS_ROUTE_PASSWORD=${NATS_ROUTE_PASSWORD}
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    networks:
      - backend
    ports:
      # for clients
      - 4222:4222
      # an HTTP management port for information reporting
      - 8222:8222
      # mqtt
      - 1883:1883
      # websocket
      - 8080:8080
    volumes:
      - $PWD/nats-server.conf:/etc/nats/nats-server.conf:ro
      - data1:/data/jetstream
    restart:
      unless-stopped
  nats2:
    image: nats:2.6.6-alpine3.14
    command: "--name nats2 -c /etc/nats/nats-server.conf --user ${NATS_ROUTE_USERNAME} --pass ${NATS_ROUTE_PASSWORD} -js -D --routes nats-route://${NATS_ROUTE_USERNAME}:${NATS_ROUTE_PASSWORD}@nats1:6222,nats-route://${NATS_ROUTE_USERNAME}:${NATS_ROUTE_PASSWORD}@nats3:6222"
    environment:
      - NATS_ROUTE_USERNAME=${NATS_ROUTE_USERNAME}
      - NATS_ROUTE_PASSWORD=${NATS_ROUTE_PASSWORD}
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    networks:
      - backend
    ports:
      # for clients
      - 4223:4222
      # an HTTP management port for information reporting
      - 8223:8222
    volumes:
      - $PWD/nats-server.conf:/etc/nats/nats-server.conf:ro
      - data2:/data/jetstream
    restart:
      unless-stopped
  nats3:
    image: nats:2.6.6-alpine3.14
    command: "--name nats3 -c /etc/nats/nats-server.conf --user ${NATS_ROUTE_USERNAME} --pass ${NATS_ROUTE_PASSWORD} -js -D --routes nats-route://${NATS_ROUTE_USERNAME}:${NATS_ROUTE_PASSWORD}@nats1:6222,nats-route://${NATS_ROUTE_USERNAME}:${NATS_ROUTE_PASSWORD}@nats2:6222"
    environment:
      - NATS_ROUTE_USERNAME=${NATS_ROUTE_USERNAME}
      - NATS_ROUTE_PASSWORD=${NATS_ROUTE_PASSWORD}
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    networks:
      - backend
    ports:
      # for clients
      - 4224:4222
      # an HTTP management port for information reporting
      - 8224:8222
    volumes:
      - $PWD/nats-server.conf:/etc/nats/nats-server.conf:ro
      - data3:/data/jetstream
    restart:
      unless-stopped

# networks
networks:
  backend:
    driver: bridge

volumes:  
  data1:
  data2:
  data3:
