version: "3.8"
services:
  nats1:
    image: nats:2.6.6-alpine3.14
    command: "-name nats1 -c /etc/nats/nats-server1.conf -js -D"
    networks:
      - backend
    ports:
      # for clients
      - 4222:4222
      # an HTTP management port for information reporting
      - 8222:8222
    volumes:
      - "$PWD/nats-server1.conf:/etc/nats/nats-server1.conf:ro"
      - "data1:/data/jetstream"
  nats2:
    image: nats:2.6.6-alpine3.14
    command: "-name nats2 -c /etc/nats/nats-server2.conf -js -D"
    networks:
      - backend
    ports:
      # for clients
      - 4223:4222
      # an HTTP management port for information reporting
      - 8223:8222
    volumes:
      - "$PWD/nats-server2.conf:/etc/nats/nats-server2.conf:ro"
      - "data2:/data/jetstream"
  nats3:
    image: nats:2.6.6-alpine3.14
    command: "-name nats3 -c /etc/nats/nats-server3.conf -js -D"
    networks:
      - backend
    ports:
      # for clients
      - 4224:4222
      # an HTTP management port for information reporting
      - 8224:8222
    volumes:
      - "$PWD/nats-server3.conf:/etc/nats/nats-server3.conf:ro"
      - "data3:/data/jetstream"

# networks
networks:
  backend:
    driver: bridge

volumes:  
  data1:
  data2:
  data3:
