version: "3.8"

x-env:
  nats: &nats
    image: nats:2.8-alpine3.15
    environment:
      NATS_SERVER_NAME: "${NATS_SERVER_NAME}"
      NATS_ROUTE_USERNAME: "${NATS_ROUTE_USERNAME}"
      NATS_ROUTE_PASSWORD: "${NATS_ROUTE_PASSWORD}"
      NATS_USERNAME: "${NATS_USERNAME}"
      NATS_PASSWORD: "${NATS_PASSWORD}"
      MQTT_USERNAME: "${MQTT_USERNAME}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
    restart:
      unless-stopped

services:
  nats:
    <<: *nats
    command: "--name ${NATS_SERVER_NAME} -c /etc/nats/nats-single.conf -js -D"
    ports:
      # for clients
      - 4222:4222
      # an HTTP management port for information reporting
      - 8222:8222
      # mqtt
      - 1883:1883
      # websocket
      - 8080:8080
    volumes:
      - $PWD/nats-single.conf:/etc/nats/nats-single.conf:ro
      - data:/data/jetstream

volumes:  
  data:
