#
# NATS leafcluster deployment:
# - there are 2 nats groups:
#   - external group (i.e. leaf node) mean to be external NATS/MQTT/websocket pub/sub communication node with TLS enabled
#   - backend group (i.e. main cluster nodes) mean to be backend nats core/jetstream pub/sub communication cluster with TLS disabled
# - in production, there should be a gateway that route external NATS/MQTT/websocket traffic to the leaf node
#

version: "3.8"

x-env:
  nats: &nats
    image: nats:2.8-alpine3.15
    networks:
      - backend
    restart:
      unless-stopped
  environment-nats-backend: &environment-nats-backend
    MY_NATS_ROUTE_USERNAME: ${MY_NATS_ROUTE_USERNAME}
    MY_NATS_ROUTE_PASSWORD: ${MY_NATS_ROUTE_PASSWORD}
    MY_NATS_NKEY_USER: ${MY_NATS_NKEY_USER}
    MY_NATS_NKEY_SEED: ${MY_NATS_NKEY_SEED}
    MY_NATS_USERNAME: ${MY_NATS_USERNAME}
    MY_NATS_PASSWORD: ${MY_NATS_PASSWORD}
    MY_LEAFNODE_USERNAME: ${MY_LEAFNODE_USERNAME}
    MY_LEAFNODE_PASSWORD: ${MY_LEAFNODE_PASSWORD}
  environment-nats-external: &environment-nats-external
    URL_NATS1: nats://${MY_LEAFNODE_USERNAME}:${MY_LEAFNODE_PASSWORD}@nats-backend1
    URL_NATS2: nats://${MY_LEAFNODE_USERNAME}:${MY_LEAFNODE_PASSWORD}@nats-backend2
    URL_NATS3: nats://${MY_LEAFNODE_USERNAME}:${MY_LEAFNODE_PASSWORD}@nats-backend3
    MY_NATS_ROUTE_USERNAME: ${MY_NATS_ROUTE_USERNAME}
    MY_NATS_ROUTE_PASSWORD: ${MY_NATS_ROUTE_PASSWORD}
    MY_LEAFNODE_USERNAME: ${MY_LEAFNODE_USERNAME}
    MY_LEAFNODE_PASSWORD: ${MY_LEAFNODE_PASSWORD}
    MY_LEAF_USERNAME: ${MY_LEAF_USERNAME}
    MY_LEAF_PASSWORD: ${MY_LEAF_PASSWORD}
    MY_MQTT_USERNAME: ${MY_MQTT_USERNAME}
    MY_MQTT_PASSWORD: ${MY_MQTT_PASSWORD}
    MY_WEBSOCKET_USERNAME: ${MY_WEBSOCKET_USERNAME}
    MY_WEBSOCKET_PASSWORD: ${MY_WEBSOCKET_PASSWORD}

services:
  nats-backend1:
    <<: *nats
    command: "--name ${MY_NATS_SERVER_NAME}Backend1 -c /etc/nats/nats-backend.conf -js -D --user ${MY_NATS_ROUTE_USERNAME} --pass ${MY_NATS_ROUTE_PASSWORD} --routes nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats-backend2:6222,nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats-backend3:6222"
    environment:
      MY_NATS_SERVER_NAME: "${MY_NATS_SERVER_NAME}Backend1"
      <<: *environment-nats-backend
    ports:
      # for clients
      - 4223:4222
      # an HTTP management port for information reporting
      - 8223:8222
    volumes:
      - $PWD/nats-backend.conf:/etc/nats/nats-backend.conf:ro
      - $PWD/nats-single.conf:/etc/nats/nats-single.conf:ro
      - backend1:/data/jetstream
  nats-backend2:
    <<: *nats
    command: "--name ${MY_NATS_SERVER_NAME}Backend2 -c /etc/nats/nats-backend.conf -js -D --user ${MY_NATS_ROUTE_USERNAME} --pass ${MY_NATS_ROUTE_PASSWORD} --routes nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats-backend1:6222,nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats-backend3:6222"
    environment:
      MY_NATS_SERVER_NAME: "${MY_NATS_SERVER_NAME}Backend2"
      <<: *environment-nats-backend
    ports:
      # for clients
      - 4224:4222
      # an HTTP management port for information reporting
      - 8224:8222
    volumes:
      - $PWD/nats-backend.conf:/etc/nats/nats-backend.conf:ro
      - $PWD/nats-single.conf:/etc/nats/nats-single.conf:ro
      - backend2:/data/jetstream
  nats-backend3:
    <<: *nats
    command: "--name ${MY_NATS_SERVER_NAME}Backend3 -c /etc/nats/nats-backend.conf -js -D --user ${MY_NATS_ROUTE_USERNAME} --pass ${MY_NATS_ROUTE_PASSWORD} --routes nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats-backend1:6222,nats-route://${MY_NATS_ROUTE_USERNAME}:${MY_NATS_ROUTE_PASSWORD}@nats-backend2:6222"
    environment:
      MY_NATS_SERVER_NAME: "${MY_NATS_SERVER_NAME}Backend3"
      <<: *environment-nats-backend
    ports:
      # for clients
      - 4225:4222
      # an HTTP management port for information reporting
      - 8225:8222
    volumes:
      - $PWD/nats-backend.conf:/etc/nats/nats-backend.conf:ro
      - $PWD/nats-single.conf:/etc/nats/nats-single.conf:ro
      - backend3:/data/jetstream
  nats-external:
    <<: *nats
    command: "--name ${MY_NATS_SERVER_NAME}External -c /etc/nats/nats-external.conf -js -D"
    environment:
      MY_NATS_SERVER_NAME: "${MY_NATS_SERVER_NAME}External"
      <<: *environment-nats-external
    ports:
      # for clients
      - 4222:4222
      # an HTTP management port for information reporting
      - 8222:8222
      # mqtt
      - 8883:8883
    volumes:
      - $PWD/nats-external.conf:/etc/nats/nats-external.conf:ro
      - $PWD/cert/my-domain.com/ca.crt:/etc/nats/nats/ca.crt:ro
      - $PWD/cert/my-domain.com/server.crt:/etc/nats/nats/server.crt:ro
      - $PWD/cert/my-domain.com/server.key:/etc/nats/nats/server.key:ro
      - $PWD/cert/my-domain.com/ca.crt:/etc/nats/mqtt/ca.crt:ro
      - $PWD/cert/my-domain.com/server.crt:/etc/nats/mqtt/server.crt:ro
      - $PWD/cert/my-domain.com/server.key:/etc/nats/mqtt/server.key:ro
      - external:/data/jetstream

# networks
networks:
  backend:
    driver: bridge

volumes:  
  backend1:
  backend2:
  backend3:
  external:
