version: "3"

services:
  #
  # etcd
  # Single node etcd service
  #
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.13
    image: "docker.io/bitnami/etcd:3-debian-10"
    networks:
      - net-all-services
    ports:
      # for debug purpose only
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
    volumes:
      - etcd-data:/etcd-data

# Names our volume
volumes:
  etcd-data:
