version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - loki
    volumes:
      - $PWD/loki-local-config.yml:/etc/loki/local-config.yml:ro

  promtail:
    image: grafana/promtail:2.3.0
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    volumes:
      - /var/log:/var/log

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
