---
- name: set rc variables
  set_fact:
    # target user's .bashrc
    bashrc: "/home/{{ vm_username }}/.bashrc"
    # target user's .vimrc
    vimrc: "/home/{{ vm_username }}/.vimrc"
- name: add alias ll
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: "{{ bashrc }}"
    regexp: "alias ll=.*"
    insertafter: 'alias '
    line: "alias ll='ls -hlF --group-directories-first'"
    create: yes
- name: add alias ll comment
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: "{{ bashrc }}"
    insertbefore: "alias ll=.*"
    line: '# add some more ls aliases'

- name: export DOCKER_ID
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: "{{ bashrc }}"
    regexp: "export DOCKER_ID=.*"
    insertafter: 'export '
    line: "export DOCKER_ID={{docker_id}}"
    create: yes
- name: add export DOCKER_ID comment
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: "{{ bashrc }}"
    insertbefore: "export DOCKER_ID=.*"
    line: '# default development environment settings'

- name: set vimrc tabstop
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: "{{ vimrc }}"
    regexp: ":set tabstop=.*"
    line: ":set tabstop=4"
    create: yes
- name: set vimrc shiftwidth
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: "{{ vimrc }}"
    regexp: ":set shiftwidth=.*"
    line: ":set shiftwidth=4"
    create: yes
