# References:
# - https://phoenixnap.com/kb/nfs-docker-volumes#:~:text=Volumes%20are%20existing%20directories%20on,NFS%20remote%20file%2Dsharing%20system.
# - https://blog.stefandroid.com/2021/03/03/mount-nfs-share-in-docker-compose.html
# - https://github.com/ContainX/docker-volume-netshare
# - https://www.thegeekdiary.com/common-nfs-mount-options-in-linux/
version: "3.8"
services:
  #
  # app-1a
  #
  app-1a:
    image: alpine:3.15
    command: sleep 100m
    volumes:
      - type: volume
        source: app1
        target: /mnt/nfs
    networks:
      - app1
  #
  # app-1b
  #
  app-1b:
    image: alpine:3.15
    command: sleep 100m
    volumes:
      - type: volume
        source: app1
        target: /mnt/nfs
    networks:
      - app1

volumes:
  app1:
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=localhost,nolock,soft,rw
      device: ":/app"

# networks
networks:
  app1:
    driver: bridge
