# References:
# - https://blog.ruanbekker.com/blog/2020/09/20/setup-a-nfs-server-with-docker/
# - https://hub.docker.com/r/itsthenetwork/nfs-server-alpine
version: "3.8"
services:
  #
  # nfs
  #
  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - nfs:/data
    networks:
      - net
    ports:
      - 2049:2049
    restart: unless-stopped
  #
  # init-nfs
  #
  init-nfs:
    image: alpine:3.15
    command: /root/init-nfs.sh
    depends_on:
      - nfs
    volumes:
      - ./init-nfs.sh:/root/init-nfs.sh:ro
      - type: volume
        source: nfsroot
        target: /mnt/nfs
        volume:
          nocopy: true
    networks:
      - net
    restart: on-failure

volumes:
  nfs:
    driver: local
  nfsroot:
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=localhost,nolock,soft,rw
      device: ":"

# networks
networks:
  net:
    driver: bridge
