version: "3.7"
services:
  #
  # consul
  # cluster of consul servers for service discovery:
  # * bootstrap as default leader with 2 server nodes
  #
  consul-bootstrap:
    image: consul:1.7
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    ports:
      # - "8400:8400"
      - "8500:8500"
      # - "8600:8600"
      # - "8600:8600/udp"
  consul-server2:
    image: consul:1.7
    command: "agent -server -retry-join consul-bootstrap -client 0.0.0.0"
    depends_on:
      - consul-bootstrap
  consul-server3:
    image: consul:1.7
    command: "agent -server -retry-join consul-bootstrap -client 0.0.0.0"
    depends_on:
      - consul-bootstrap
