---
- name: Prepare docker swarm nodes
  hosts: all
  roles:
    - create-sudo-user
    - update-all
    - init-user
    - install-git
    - install-modules
    - enable-firewalld

- name: Install docker to all nodes
  hosts: all
  roles:
    - install-docker
    - add-user-docker-group

#FIXME, install docker plugins (i.e. Loki)
#FIXME, install docker manager and worker nodes
#FIXME, install monitoring stack with Grafana and Prometheus
