---
- name: Install Packages
  become: true
  become_user: root
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - epel-release
    - openssh-server
    - net-tools
    - tree
    - jq
    - openssl
    - curl
