---
- name: install epel-release
  become: true
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - epel-release
- name: upgrade all packages after installing epel-release
  become: true
  become_user: root
  yum:
    name=*
    state=latest
- name: install packages
  become: true
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - openssh-server
    - net-tools
    - tree
    - jq
    - openssl
    - curl
    - python
    - python-pip
