---
- name: install packages
  become: true
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - epel-release
    - openssh-server
    - net-tools
    - tree
    - jq
    - openssl
    - curl
    - python
    - python-pip
