---
# - name: debug print hostname and node_labels
#   debug:
#     msg: "hostname: {{ item.0.key }} node_labels: {{ item.1 }}"
#   loop: "{{ hostvars | dict2items | subelements('value.node_labels') }}"

- name: label docker node
  shell: docker node update --label-add {{ item.1 }} {{ item.0.key }}
  loop: "{{ hostvars | dict2items | subelements('value.node_labels') }}"
