version: '3.8'
services:
  #
  # traefik
  #
  traefik:
    image: traefik:2.8
    command:
      # docker configuration
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.file.filename=/etc/traefik/conf/dynamic.yml"
      - "--providers.file.watch=true"
      # entrypoint configuration
      - "--entrypoints.whoami.address=:4222"
      # log output of: DEBUG, INFO, WARN, ERROR, PANIC, and FATAL
      - "--log.level=INFO"
    networks:
      - frontend
    ports:
      # whoami
      - 4222:4222
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik/conf/:ro
  #
  # whoami
  #
  whoami:
    image: ${DOCKER_ID}/whoami:latest
    environment:
      MY_PORT: "4222"
      MY_CA_FILENAME: cert/kamching.freemyip.com/ca.crt
      MY_CERT_FILENAME: cert/kamching.freemyip.com/server.crt
      MY_KEY_FILENAME: cert/kamching.freemyip.com/server.key
    networks:
      - frontend
    volumes:
      - ./whoami/cert/kamching.freemyip.com/:/app/cert/kamching.freemyip.com/
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.whoami.entrypoints=whoami"
      - "traefik.tcp.routers.whoami.rule=HostSNI(`whoami.kamching.freemyip.com`)"
      - "traefik.tcp.routers.whoami.service=whoami"
      - "traefik.tcp.routers.whoami.tls.passthrough=true"
      - "traefik.tcp.services.whoami.loadbalancer.server.port=4222"
    deploy:
      replicas: 3

# networks
networks:
  frontend:
    driver: bridge
