---
- name: set init_manager
  set_fact:
    init_manager: "{{ groups['docker_init_manager'][0] }}"

- name: set init_manager ip and token
  set_fact:
    init_manager_ip: "{{ hostvars[init_manager]['ansible_default_ipv4']['address'] }}"
    init_manager_token: "{{ hostvars[init_manager]['manager_token']['stdout'] }}"

- name: check if swarm is already initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: add managers to the swarm
  when: swarm_status.rc != 0
  shell: docker swarm join --token {{ init_manager_token }} {{ init_manager_ip }}:2377
