---
- name: get docker user username
  set_fact:
    vm_username: "{{ lookup('env', 'VM_USERNAME') }}"

- name: add user to docker group
  become: true
  become_user: root
  user:
    name: "{{ vm_username }}"
    groups: docker
    append: yes
