version: '3.9'
services:
  #
  # proxy
  #
  proxy:
    image: traefik:3.0
    command:
      # docker configuration
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=whoami2_proxy"
      - "--entryPoints.web.address=:80"
      # disable dashboard
      - "--api.dashboard=false"
      - "--api.insecure=false"
      # log output of: DEBUG, INFO, WARN, ERROR, PANIC, and FATAL
      - "--log.level=INFO"
    restart: unless-stopped
    networks:
      - proxy
    ports:
      # docker sends requests on this port to traefik
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  #
  # whoami
  #
  whoami:
    image: containous/whoami:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`wk.ldev.wahkwong.com.hk`)

networks:
  proxy:
    driver: bridge
