version: '3.8'
services:
  #
  # traefik
  #
  traefik:
    command:
      # docker configuration
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.network=proxy_net"
      - "--providers.file.filename=/etc/traefik/conf/dynamic.yml"
      - "--providers.file.watch=true"
      # configure entrypoint; redirect all http links to https
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      # acme configurations
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=freemyip"
      # enable api and dashboard
      - "--api.dashboard=true"
      # enable log output
      - "--log.level=INFO"
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/conf/dynamic.yml:ro
      - ./acme:/etc/traefik/acme
    restart: always
    labels:
      - "traefik.enable=true"
        # traefik dashboard: https://proxy.kamching.freemyip.com/dashboard/
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`proxy.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-dashboard.middlewares=admin-auth@file"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"

networks:
  net:
    driver: bridge
