version: '3.8'
services:
  #
  # traefik
  #
  traefik:
    image: traefik:2.6
    environment:
      - FREEMYIP_TOKEN=$FREEMYIP_TOKEN
    networks:
      - net
    ports:
      # docker sends requests on this port to traefik
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
