version: "3.7"
services:
  #
  # mysql
  #
  mysql:
    container_name: ims_customer_portal_db
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_DBNAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
  #
  # Database Web Management
  #
  admin:
    image: adminer
    ports:
      - '8080:8080'

volumes:  
  database:
