# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_BOX = "centos/7"
VM_PROVIDER = "virtualbox"
VM_BRIDGE = ENV['VAGRANT_BRIDGE']
VM_USERNAME = ENV['VM_USERNAME']
VM_PASSWORD = ENV['VM_PASSWORD']

# setup docker swarm cluster with vagrant
# - manager: docker swarm manager node
# - worker docker swarm worker node
cluster = {
  "manager" => { :num => 2, :cpus => 1, :mem => 1024 },
  "worker" => { :num => 3, :cpus => 1, :mem => 1024 }
}

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network "public_network", bridge: VM_BRIDGE, auto_config: true

  cluster.each_with_index do |(hostname, info), index|
    (1..info[:num]).each do |i|
      config.vm.define hostname + "-#{i}" do |cfg|
        cfg.vm.provider VM_PROVIDER do |vb|
          vb.name = "#{hostname}-#{i}"
          vb.cpus = info[:cpus]
          vb.memory = info[:mem]
        end
        config.vm.hostname = "#{hostname}-#{i}"
        config.vm.provision "shell", inline: <<-SHELL
          sudo yum update -y
          sudo yum upgrade -y
          sudo yum install vim -y
          sudo yum install git -y
          sudo adduser -m -U #{VM_USERNAME}
          echo #{VM_PASSWORD} | sudo passwd #{VM_USERNAME} --stdin
          sudo usermod -aG wheel #{VM_USERNAME}
        SHELL
      end
    end
  end

end
