# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_BOX = "centos/7"
VM_PROVIDER = "virtualbox"
VM_BRIDGE = ENV['VAGRANT_BRIDGE']

# setup cluster of VMswith vagrant
cluster = {
  "manager" => { :num => 2, :cpus => 1, :mem => 1024 },
  "worker" => { :num => 3, :cpus => 1, :mem => 1024 },
}

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network "public_network", bridge: VM_BRIDGE, auto_config: true

  cluster.each_with_index do |(hostname, info), index|
    (1..info[:num]).each do |i|
      config.vm.define hostname + "-#{i}" do |cfg|
        cfg.vm.provider VM_PROVIDER do |vb|
          vb.name = "#{hostname}-#{i}"
          vb.cpus = info[:cpus]
          vb.memory = info[:mem]
          config.vm.hostname = "#{hostname}-#{i}"
        end
        config.vm.provision "shell", inline: <<-SHELL
          sudo yum update -y
          sudo yum upgrade -y
        SHELL
      end
    end
  end

end
