# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_BOX = "centos/7"
VM_PROVIDER = "virtualbox"
BRIDGE = ENV['VAGRANT_BRIDGE']

# setup docker swarm cluster with vagrant
# - manager: docker swarm manager node
# - worker docker swarm worker node
cluster = {
  "manager" => { :num => 2, :cpus => 1, :mem => 1024 },
  "worker" => { :num => 3, :cpus => 1, :mem => 1024 }
}

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network "public_network", bridge: BRIDGE, auto_config: true

  cluster.each_with_index do |(hostname, info), index|
    (1..info[:num]).each do |i|
      config.vm.define hostname + "-#{i}" do |cfg|
        cfg.vm.provider VM_PROVIDER do |vb, override|
          vb.name = hostname + "-#{i}"
          vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
          override.vm.hostname = hostname + "-#{i}"
        end
      end
    end
  end

end
