---
- name: install-loki preparation
  set_fact:
    plugin: grafana/loki-docker-driver
    tag: latest
    alias: loki
    opts: --grant-all-permissions

- name: check if docker plugin loki has already been initialized
  shell: docker plugin list --format '{{ '{{' }} .Name {{ '}}' }}' | grep loki
  register: loki_status
  ignore_errors: true

- name: install docker plugin
  become: true
  become_user: root
  when: loki_status.rc != 0
  shell: docker plugin install {{ plugin }}:{{ tag }} --alias {{ alias }} {{ opts }} 
  notify:
    - restart docker service

# Note:
# - as docker plugin does not support network overlay
# - so, it cannot refer to the loki server through docker's dns
# - instead, modify host file to refer to the loki server
# Reference:
# - https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html
- name: set loki server ip address
  set_fact:
    loki_ip: "{{ (hostvars | dict2items | selectattr('value.node_labels', 'contains', 'loki=true') | first).value.ansible_host }}"

- name: dns add entry loki ip
  become: true
  lineinfile:
    path: "/etc/hosts"
    regexp: "{{ loki_ip }} loki"
    insertafter: EOF
    line: "{{ loki_ip }} loki"
    create: yes
